image: maven:3.9-amazoncorretto-23

stages:
  - test
  - deploy

analyze-tests:
  stage: test
  tags:
    - axl
  script:
    - mvn clean test
  artifacts:
    paths:
      - target/site/jacoco/
    reports:
      junit: target/surefire-reports/*.xml
  cache:
    paths:
      - .m2/repository

deploy-jacoco:
  stage: deploy
  tags:
    - axl
  script:
    - yum install -y sshpass
    - sshpass -p "$SSH_PASSWORD" scp -o StrictHostKeyChecking=no -r target/site/jacoco/ $SSH_USER@$SSH_HOST:/sites/jacoco/
  only:
    - main