image: openjdk:23-jdk

stages:
  - test

before_script:
  - apt update && apt install -y maven

unit-tests:
  stage: test
  script:
    - mvn --version
    - mvn clean test
  artifacts:
    reports:
      junit: target/surefire-reports/*.xml
  cache:
    paths:
      - .m2/repository/