image: maven:3.9-amazoncorretto-23

stages:
  - test
  - deploy

analyze-tests:
  stage: test
  tags:
    - axl
  script:
    - mvn clean test
  artifacts:
    paths:
      - target/site/jacoco/
    reports:
      junit: target/surefire-reports/*.xml
  cache:
    paths:
      - .m2/repository

pages:
  stage: deploy
  script:
    - mkdir public
    - cp -r target/site/jacoco/* public/
  artifacts:
    paths:
      - public