image: maven:3.9-amazoncorretto-23

stages:
  - test

analyze-tests:
  stage: test
  tags:
    - axl
  script:
    - mvn clean test
  artifacts:
    reports:
      junit: target/surefire-reports/*.xml
  cache:
    paths:
      - .m2/repository
