image: maven:3.9-amazoncorretto-23

stages:
  - test

analyze-tests:
  stage: test
  tags:
    - axl
  script:
    - mvn clean test
    - mvn jacoco:report
    - java -cp target/classes:target/test-classes:$(mvn dependency:build-classpath | grep -v '\[INFO\]' | tr -d '\n') com.github.michaelruocco.jacocotojunit.JacocoToJunit target/site/jacoco/jacoco.xml target/junit-reports/jacoco-junit.xml
  artifacts:
    reports:
      junit: target/junit-reports/jacoco-junit.xml
    paths:
      - target/site/jacoco/
  cache:
    paths:
      - .m2/repository