mirror_to_github:
  stage: mirror
  image: ruby:2.7
  needs: []
  script: |
    if git log -1 --pretty=format:'%s' | grep -q 'Mirrored from GitHub'; then
      echo "::set-output name=is_mirrored::true"
    else
      echo "::set-output name=is_mirrored::false"
    fi

    git remote add gitlab https://SoraVWV:$GITHUB_TOKEN@github.com/SoraVWV/axl.git
    git push --mirror gitlab

    echo "Mirrored from GitLab" | git commit --allow-empty -F -
    git push origin

  variables:
    GITHUB_TOKEN: $GITHUB_TOKEN
