mirror_to_github:
  stage: mirror
  image: ruby:2.7
  needs: []
  script:
    - echo "Checking if commit is from GitHub mirroring..."
    - if git log -1 --pretty=format:'%s' | grep -q 'Mirrored from GitHub'; then
      echo "Commit is from GitHub mirroring. Skipping...";
      exit 0;
      fi

    - echo "Mirroring to GitHub..."
    - git remote add github https://$GITHUB_TOKEN@github.com/lite/compiler.git
    - git push --mirror github

    - echo "Adding mirror commit message..."
    - echo "Mirrored from GitLab" | git commit --allow-empty -F -
    - git push origin
  variables:
    GITHUB_TOKEN: $GITHUB_TOKEN