package axl.compiler.utils.symboltable;

public enum JvmAccessFlag {
    PUBLIC, PRIVATE, PROTECTED, STATIC, FINAL, SYNCHRONIZED, VOLATILE,
    TRANSIENT, SUPER, INTERFACE, ABSTRACT, STRICT, SYNTHETIC, ANNOTATION,
    ENUM,
}
