name: Mirror to GitLab

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Mirror to GitLab
        run: |
          git remote add gitlab https://oauth2:$GITLAB_TOKEN@gitlab.com/username/repo.git
          git push --mirror gitlab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}