name: Mirror to GitLab

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check if commit is from GitLab mirroring
        id: check_commit
        run: |
          if git log -1 --pretty=format:'%s' | grep -q 'Mirrored from GitLab'; then
            echo "::set-output name=is_mirrored::true"
          else
            echo "::set-output name=is_mirrored::false"
          fi

      - name: Mirror to GitLab
        if: steps.check_commit.outputs.is_mirrored == 'false'
        run: |
          git remote add gitlab https://oauth2:$GITLAB_TOKEN@gitlab.axolotl-lang.ru/compiler/lite.git
          git push --mirror gitlab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}